IMAGE_NAME = "ubuntu/bionic64"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end


    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 9}"
            node.vm.hostname = "rancher-node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "rancher-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 9}",
                }
	        # Optional config enable password authenitication ssh via vagrant
            # config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
            end
        end
    end
end

